# execute with ansible-playbook -i 'localhost,' setup/curie.yml

- hosts: localhost
  connection: local
  sudo: True
  roles:
    - common
  tasks:
    - apt: name={{item}}
      with_items:
        - dsniff

    - name: install metaploit dev dependencies
      apt: name={{item}}
      with_items:
        - build-essential
        - zlib1g
        - zlib1g-dev
        - libxml2
        - libxml2-dev
        - libxslt-dev
        - locate
        - libreadline6-dev
        - libcurl4-openssl-dev
        - git-core
        - libssl-dev
        - libyaml-dev
        - openssl
        - autoconf
        - libtool
        - ncurses-dev
        - bison
        - curl
        - wget
        - xsel
        - postgresql
        - postgresql-contrib
        - libpq-dev
        - libapr1
        - libaprutil1
        - libsvn1
        - libpcap-dev
        - libsqlite3-dev

  # todo nbtscan