# execute with ansible-playbook -i 'localhost,' setup/feynman.yml

- hosts: localhost
  connection: local
  sudo: True
  vars:
    crashplan:
      version: 4.4.1
      sha256: 0bb24c88152f0f523e17d9a0df8013567f29f882538a45524fe440ef170d787a
    git:
      signingkey: B3BF75A0
  roles:
    - common
  tasks:
    - name: Download rescuetime
      get_url: url="https://www.rescuetime.com/installers/rescuetime_current_amd64.deb" dest=/tmp/rescuetime.deb

    - name: Install rescuetime
      apt: deb=/tmp/rescuetime.deb

    - name: Install xen
      apt: name=xen-hypervisor-amd64

    - name: Do not override the normal linux kernel with xens
      lineinfile: dest=/etc/default/grub.d/xen.cfg regexp='^(#)?XEN_OVERRIDE_GRUB_DEFAULT' line='XEN_OVERRIDE_GRUB_DEFAULT=0' backup=yes

    - name: Check if crashplan is already installed
      stat: path=/usr/local/bin/CrashPlanDesktop
      register: crashplan

    - name: Download crashplan
      when: not crashplan.stat.exists
      get_url: url="http://download.code42.com/installs/linux/install/CrashPlan/CrashPlan_{{crashplan.version}}_Linux.tgz" dest=/tmp/crashplan.tgz sha256sum={{crashplan.sha256}}

    - name: Extract crashplan
      when: not crashplan.stat.exists
      unarchive: src=/tmp/crashplan.tgz copy=no dest=/tmp/

    - name: Ensure no incompatible OpenJDK # Make sure that Crashplan will use its own Oracle JDK
      when: not crashplan.stat.exists
      apt: name=openjdk-7-jre-headless state=absent

    - name: Increase inotify watches
      # lineinfile: dest=/proc/sys/fs/inotify/max_user_watches regexp='' line=" 1500000" # doesn't work
      shell: echo "1500000" | tee /proc/sys/fs/inotify/max_user_watches

    - name: Install crashplan
      when: not crashplan.stat.exists
      shell: xterm ./install.sh chdir=/tmp/crashplan-install

    - name: Increase inotify watches (persist)
      lineinfile: dest=/etc/sysctl.conf line="fs.inotify.max_user_watches=1500000"
